### ISSUE TITLE
Use instantiated service instead of custom unit

### ISSUE THREAD

**Issue by Alveel** [evrardjp/ansible-tinc#18]
The supported distributions of this module all allow instantiated services. That is, for example, `tinc@${netname}.service` will automatically start the `$netname` net, assuming it is found in `/etc/tinc`.

Would it be an idea to use that instead of providing a custom unit file?

Besides that, thank you for writing this role, it does exactly what it should do!

**Comment by evrardjp** [comment]
I think that's a fair idea.

I would be happy to see a PR on it, as I am not sure I have the bandwidth to write and test it right now.

**Comment by Alveel** [comment]
Hi! Sorry for the delay in my response... I hope to be able to do work on this within a few weeks time. I think we can close it until then :)
