### ISSUE TITLE
Handler Casing mismatch

### ISSUE THREAD

**Issue by Routhinator** [evrardjp/ansible-tinc#2]
Task "create tinc systemd service file" references handler "Restart Service" however handler is defined as "Restart service"

Error:
```
ERROR! The requested handler 'Restart Service' was not found in either the main handlers list nor in the listening handlers list
```

**Comment by evrardjp** [comment]
Fixed. Sorry for the delay, I got no notifications from github?!

**Comment by evrardjp** [comment]
This should be fixed now.

**Comment by sedlund** [comment]
ansible galaxy is referencing tag 0.1.1 which doesnt have this fix.

**Comment by evrardjp** [comment]
done.
