### ISSUE TITLE
Who sets tinc_control_plane_bind_ip?

### ISSUE THREAD

**Issue by apinnecke** [evrardjp/ansible-tinc#3]
In https://github.com/evrardjp/ansible-tinc/blob/master/tasks/tinc_configure.yml#L41 the ansible variable `tinc_control_plane_bind_ip` is used but never gets set or defined or initialized. Could you please explain how this variable is handled? I would have expected that `ansible_default_ipv4.address` or something similar is used. :)

Thanks in advance!

**Comment by domhaas** [comment]
Got the same issue. Instead of this not defined var you can use the current host ip for that, like: `{{ ansible_host }}` or `{{ ansible_eth0.ipv4.address }}`. Then for me it works perfectly.

**Comment by evrardjp** [comment]
I added it in the documentation. Sorry I completely missed that ping.
