### ISSUE TITLE
fails at "sync the fetched tinc hosts files on each host"

### ISSUE THREAD

**Issue by raoel** [evrardjp/ansible-tinc#53]
fails on this task:

TASK [evrardjp.tinc: sync the fetched tinc hosts files on each host]                   

fatal: [pi2]: FAILED! => {"changed": false, "cmd": "/bin/rsync --delay-updates -F --compress --archive --rsh=/bin/ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -C -o ControlMaster=auto -o ControlPersist=60s --chown=root:root --out-format=<<CHANGED>>%i %n%L /home/roomen/raoel/ansible/fetch/ user@192.168.1.182:/etc/tinc/k3s/hosts/", "msg": "Warning: Permanently added '192.168.1.182' (ECDSA) to the list of known hosts.\r\nrsync: failed to set times on \"/etc/tinc/k3s/hosts/.\": Operation not permitted (1)\nrsync: mkstemp \"/etc/tinc/k3s/hosts/.pi1.6VrCca\" failed: Permission denied (13)\nrsync: mkstemp \"/etc/tinc/k3s/hosts/.pi2.Ou08fa\" failed: Permission denied (13)\nrsync: mkstemp \"/etc/tinc/k3s/hosts/.pi3.80P1ja\" failed: Permission denied (13)\nrsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1330) [sender=3.2.3]\n", "rc": 23}

looks like rsync is failing?  could it be related to this issue?  https://github.com/ansible/ansible/issues/15297

I did not add "nopasswd" for rsync to my sudoers fle....

**Comment by evrardjp** [comment]
it looks more like a permission issue to write into that folder with rsync. It's not from the role per-se. Can you try running rsync directly, chowing to root (as you mention in your logs)? What are your ansible connection settings?

**Comment by evrardjp** [comment]
Alternatively, as synchronize has always been a pain to deal with on embedded devices, we might want to refactor the role to have:
- adding a task to read the file content, registering it.
- adding a task to generate the file content based on other node's facts by looping over the groups.
- removing the synchronize tasks.

What do you think?

**Comment by raoel** [comment]
- rsync fails between 2 hosts fails.

So I tried ssh with option -A (agent forwarding).
Now, as user "raoel" I can sync, this works:

`rsync -a  test123 raoel@192.168.1.182:.`

When I try this as root (`sudo !!`) it fails because root user cannot use my ssh-agent forwarding.

Yeah, it sounds like the gathering of hosts-files should be done in the tasks, registering it sounds like a good plan, and then loop over the hosts. "synchronize" is a lot of issues to get working reliably.

**Comment by evrardjp** [comment]
Well, it was working before, but I sadly didn't invest more time in maintaining this one. I am welcoming any help.
I am particularly looking for any change to make it more reliable on different distros, and increase the test coverage with molecule. I can pair with the people that want to implement it :)
